name: Docker Image CI

on:
  workflow_call:
    secrets:
      npmrc2:
        required: false

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: nasty hack to evaluate if secret is passed to the workflow
    # this uses a secret as an output to properly evalueate if it's even set!
      id: nasty_hack
      run : echo '::set-output name=npmrc::${{secrets.npmrc2}}'
    - name: setup-npmrc
      if: ${{ steps.nasty_hack.outputs.npmrc }}
      run: echo ${{ steps.nasty_hack.outputs.npmrc }} > ./.npmrc
    - name: Build the Docker image
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag my-image-name:$TAG --network=host
