name: Docker Image CI

on:
  workflow_call:
    inputs:
      npmrc:
        required: false

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: fetch-npmrc
      if: ${{ inputs.npmrc }}
      run: echo ${{ inputs.npmrc }} > ./.npmrc
    - name: Build the Docker image
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag my-image-name:$TAG --network=host
